//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTIC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectView
    {
        public string Surname { get; set; }
        public string Name1 { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public string Dedcription { get; set; }
    }
}
